### ISSUE TITLE
[BUG] date input

### ISSUE THREAD

**Issue by stgov** [OlivierBinette/streamlit-survey#10]
![image](https://github.com/Valires/streamlit-survey/assets/78441999/91c112fa-09a8-4169-869c-7b5cf42a9124)
hi, the streamlit date_input has an arg for the date format and you can set the date to None as defualt value, could you add it please?

```py
nacimiento = survey.dateinput(
            ':red[*]Fecha de nacimiento',
            key='nacimiento',
            value=None, # it does not work
            min_value=datetime.now() - timedelta(days=365 * 100),
            max_value=datetime.now(),
            format='DD/MM/YYYY', # it does not work
        )
```

**Comment by OlivierBinette** [comment]
Fixed, thank you!
