### ISSUE TITLE
[FEAT] Change place holders on survey multiselect

### ISSUE THREAD

**Issue by stgov** [OlivierBinette/streamlit-survey#11]
![image](https://github.com/Valires/streamlit-survey/assets/78441999/2a91c129-6078-4f1a-9647-467d04a5f1af)
Could i change the text that says "Chose an option"?,
i am developing a survey in Spanish and the public of the survey does not know English

**Comment by OlivierBinette** [comment]
@stgov You should be able to use all parameters from the Streamlit base component: https://docs.streamlit.io/library/api-reference/widgets/st.selectbox

Can you try this and let me know if it works?

**Comment by stgov** [comment]
i get this error

![image](https://github.com/Valires/streamlit-survey/assets/78441999/94e5a383-67e4-4692-98ca-bf0a27dc508e)

**Comment by OlivierBinette** [comment]
The error you see is raised from Streamlit. Are you using the latest streamlit version? You can do `pip show streamlit` to see what version you have installed.

**Comment by stgov** [comment]
That's it! I was using version 1.24. Thank you very much!
