### ISSUE TITLE
[BUG] Pip version outdated

### ISSUE THREAD

**Issue by justin13601** [OlivierBinette/streamlit-survey#12]
## Describe the bug
The pip version seems to be oudated despite the version number being the same. I checked the code files from the repo vs. the ones installed from pip and it seems like many items are missing.

## To Reproduce
```
pip install streamlit-survey
```
vs.
```
pip install --force-reinstall git+https://github.com/OlivierBinette/streamlit-survey
```

## Expected behavior
Code files should match

## Additional context
Until fixed, we can just install from github repo

**Comment by OlivierBinette** [comment]
@justin13601 Thanks for letting me know! I'll make an update within the next few days, and then close this issue.

**Comment by OlivierBinette** [comment]
Resolved
