### ISSUE TITLE
[FEAT] modify the next page button

### ISSUE THREAD

**Issue by stgov** [OlivierBinette/streamlit-survey#8]
hi, how do i change the label on the next page or the submit button?, how i disable or enable them?

**Comment by OlivierBinette** [comment]
Hi @stgov, could you tell me more about the features you'd like and how you would like to see them implemented? I will make an update.

**Comment by stgov** [comment]
![Captura de pantalla 2023-07-17 232118](https://github.com/Valires/streamlit-survey/assets/78441999/83170de1-0c25-44db-a153-9ae27b3daf39)
Can I change the text of those buttons, and disable them if some condition is not met?

**Comment by OlivierBinette** [comment]
Hi @stgov, I pushed an update to Streamlit-Survey that lets you change the buttons. See at the bottom of the "Advanced Usage" documentation page: https://olivierbinette-streamlit-surv-docs-streamlit-survey-docs-hu1jf8.streamlit.app/Advanced_Usage

Let me know what you think!

**Comment by stgov** [comment]
Thanks!! that was very quick, The feature has been spot-on and exactly what I was looking for

**Comment by OlivierBinette** [comment]
I'm glad it helped! I'll publish the update to PyPI in a few days.

Let me know if you have other feature ideas. Always looking to improve the package.
